/* automatically generated by rust-bindgen 0.66.1 */

#![allow(rustdoc::bare_urls)]
#![allow(rustdoc::broken_intra_doc_links)]
#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]

use crate::es::sys::es_format_t;
use crate::meta::sys::{vlc_meta_t, vlc_meta_type_t};
use crate::object::sys::vlc_object_t;
use crate::threads::vlc_mutex_t;
use crate::tick::sys::vlc_tick_t;

#[repr(C)]
#[derive(Default)]
pub struct __IncompleteArrayField<T>(::std::marker::PhantomData<T>, [T; 0]);
impl<T> __IncompleteArrayField<T> {
    #[inline]
    pub const fn new() -> Self {
        __IncompleteArrayField(::std::marker::PhantomData, [])
    }
    #[inline]
    pub fn as_ptr(&self) -> *const T {
        self as *const _ as *const T
    }
    #[inline]
    pub fn as_mut_ptr(&mut self) -> *mut T {
        self as *mut _ as *mut T
    }
    #[inline]
    pub unsafe fn as_slice(&self, len: usize) -> &[T] {
        unsafe { ::std::slice::from_raw_parts(self.as_ptr(), len) }
    }
    #[inline]
    pub unsafe fn as_mut_slice(&mut self, len: usize) -> &mut [T] {
        unsafe { ::std::slice::from_raw_parts_mut(self.as_mut_ptr(), len) }
    }
}
impl<T> ::std::fmt::Debug for __IncompleteArrayField<T> {
    fn fmt(&self, fmt: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        fmt.write_str("__IncompleteArrayField")
    }
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct input_attachment_t {
    _unused: [u8; 0],
}
extern "C" {
    pub fn input_item_WriteMeta(
        arg1: *mut vlc_object_t,
        arg2: *mut input_item_t,
    ) -> ::std::os::raw::c_int;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct vlc_epg_event_t {
    pub i_start: i64,
    pub i_duration: u32,
    pub i_id: u16,
    pub psz_name: *mut ::std::os::raw::c_char,
    pub psz_short_description: *mut ::std::os::raw::c_char,
    pub psz_description: *mut ::std::os::raw::c_char,
    pub description_items: *mut vlc_epg_event_t__bindgen_ty_1,
    pub i_description_items: ::std::os::raw::c_int,
    pub i_rating: u8,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct vlc_epg_event_t__bindgen_ty_1 {
    pub psz_key: *mut ::std::os::raw::c_char,
    pub psz_value: *mut ::std::os::raw::c_char,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct vlc_epg_t {
    pub psz_name: *mut ::std::os::raw::c_char,
    pub i_id: u32,
    pub i_source_id: u16,
    pub i_event: usize,
    pub pp_event: *mut *mut vlc_epg_event_t,
    pub b_present: bool,
    pub p_current: *const vlc_epg_event_t,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct vlc_list {
    pub prev: *mut vlc_list,
    pub next: *mut vlc_list,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct input_item_opaque {
    _unused: [u8; 0],
}
pub type input_item_opaque_t = input_item_opaque;
pub type input_item_slave_t = input_item_slave;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct info_category_t {
    pub psz_name: *mut ::std::os::raw::c_char,
    pub infos: vlc_list,
    pub node: vlc_list,
}
#[repr(u32)]
#[non_exhaustive]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum input_item_type_e {
    ITEM_TYPE_UNKNOWN = 0,
    ITEM_TYPE_FILE = 1,
    ITEM_TYPE_DIRECTORY = 2,
    ITEM_TYPE_DISC = 3,
    ITEM_TYPE_CARD = 4,
    ITEM_TYPE_STREAM = 5,
    ITEM_TYPE_PLAYLIST = 6,
    ITEM_TYPE_NODE = 7,
    ITEM_TYPE_NUMBER = 8,
}
#[repr(C)]
pub struct input_item_es {
    pub es: es_format_t,
    pub id: *mut ::std::os::raw::c_char,
    pub id_stable: bool,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct input_item_es_vector {
    pub cap: usize,
    pub size: usize,
    pub data: *mut input_item_es,
}
#[repr(C)]
pub struct input_item_t {
    pub psz_name: *mut ::std::os::raw::c_char,
    pub psz_uri: *mut ::std::os::raw::c_char,
    pub i_options: ::std::os::raw::c_int,
    pub ppsz_options: *mut *mut ::std::os::raw::c_char,
    pub optflagv: *mut u8,
    pub optflagc: ::std::os::raw::c_uint,
    pub opaques: *mut input_item_opaque_t,
    pub i_duration: vlc_tick_t,
    pub categories: vlc_list,
    pub es_vec: input_item_es_vector,
    pub p_stats: *mut input_stats_t,
    pub p_meta: *mut vlc_meta_t,
    pub i_epg: ::std::os::raw::c_int,
    pub pp_epg: *mut *mut vlc_epg_t,
    pub i_epg_time: i64,
    pub p_epg_table: *const vlc_epg_t,
    pub i_slaves: ::std::os::raw::c_int,
    pub pp_slaves: *mut *mut input_item_slave_t,
    pub lock: vlc_mutex_t,
    pub i_type: input_item_type_e,
    pub b_net: bool,
    pub i_preparse_depth: ::std::os::raw::c_int,
    pub b_preparse_interact: bool,
    pub libvlc_owner: *mut ::std::os::raw::c_void,
}
#[repr(u32)]
#[non_exhaustive]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum input_item_net_type {
    ITEM_NET_UNKNOWN = 0,
    ITEM_NET = 1,
    ITEM_LOCAL = 2,
}
#[repr(u32)]
#[non_exhaustive]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum slave_type {
    SLAVE_TYPE_SPU = 0,
    SLAVE_TYPE_GENERIC = 1,
}
#[repr(u32)]
#[non_exhaustive]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum slave_priority {
    SLAVE_PRIORITY_MATCH_NONE = 1,
    SLAVE_PRIORITY_MATCH_RIGHT = 2,
    SLAVE_PRIORITY_MATCH_LEFT = 3,
    SLAVE_PRIORITY_MATCH_ALL = 4,
    SLAVE_PRIORITY_USER = 5,
}
#[repr(C)]
#[derive(Debug)]
pub struct input_item_slave {
    pub i_type: slave_type,
    pub i_priority: slave_priority,
    pub b_forced: bool,
    pub psz_uri: __IncompleteArrayField<::std::os::raw::c_char>,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct input_item_node_t {
    pub p_item: *mut input_item_t,
    pub i_children: ::std::os::raw::c_int,
    pub pp_children: *mut *mut input_item_node_t,
}
extern "C" {
    pub fn input_item_CopyOptions(p_child: *mut input_item_t, p_parent: *mut input_item_t);
}
extern "C" {
    pub fn input_item_SetName(p_item: *mut input_item_t, psz_name: *const ::std::os::raw::c_char);
}
extern "C" {
    pub fn input_item_node_Create(p_input: *mut input_item_t) -> *mut input_item_node_t;
}
extern "C" {
    pub fn input_item_node_AppendItem(
        p_node: *mut input_item_node_t,
        p_item: *mut input_item_t,
    ) -> *mut input_item_node_t;
}
extern "C" {
    pub fn input_item_node_AppendNode(
        p_parent: *mut input_item_node_t,
        p_child: *mut input_item_node_t,
    );
}
extern "C" {
    pub fn input_item_node_RemoveNode(
        parent: *mut input_item_node_t,
        child: *mut input_item_node_t,
    );
}
extern "C" {
    pub fn input_item_node_Delete(p_node: *mut input_item_node_t);
}
#[repr(u32)]
#[non_exhaustive]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum input_item_option_e {
    VLC_INPUT_OPTION_TRUSTED = 2,
    VLC_INPUT_OPTION_UNIQUE = 256,
}
extern "C" {
    pub fn input_item_AddOption(
        arg1: *mut input_item_t,
        arg2: *const ::std::os::raw::c_char,
        i_flags: ::std::os::raw::c_uint,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn input_item_AddOptions(
        arg1: *mut input_item_t,
        i_options: ::std::os::raw::c_int,
        ppsz_options: *const *const ::std::os::raw::c_char,
        i_flags: ::std::os::raw::c_uint,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn input_item_AddOpaque(
        arg1: *mut input_item_t,
        arg2: *const ::std::os::raw::c_char,
        arg3: *mut ::std::os::raw::c_void,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn input_item_ApplyOptions(arg1: *mut vlc_object_t, arg2: *mut input_item_t);
}
extern "C" {
    pub fn input_item_Playable(arg1: *const ::std::os::raw::c_char) -> bool;
}
extern "C" {
    pub fn input_item_slave_GetType(
        arg1: *const ::std::os::raw::c_char,
        arg2: *mut slave_type,
    ) -> bool;
}
extern "C" {
    pub fn input_item_slave_New(
        arg1: *const ::std::os::raw::c_char,
        arg2: slave_type,
        arg3: slave_priority,
    ) -> *mut input_item_slave_t;
}
extern "C" {
    pub fn input_item_AddSlave(
        arg1: *mut input_item_t,
        arg2: *mut input_item_slave_t,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn input_item_SetMeta(
        arg1: *mut input_item_t,
        meta_type: vlc_meta_type_t,
        psz_val: *const ::std::os::raw::c_char,
    );
}
extern "C" {
    pub fn input_item_MetaMatch(
        p_i: *mut input_item_t,
        meta_type: vlc_meta_type_t,
        psz: *const ::std::os::raw::c_char,
    ) -> bool;
}
extern "C" {
    pub fn input_item_GetMeta(
        p_i: *mut input_item_t,
        meta_type: vlc_meta_type_t,
    ) -> *mut ::std::os::raw::c_char;
}
extern "C" {
    pub fn input_item_GetMetaLocked(
        arg1: *mut input_item_t,
        meta_type: vlc_meta_type_t,
    ) -> *const ::std::os::raw::c_char;
}
extern "C" {
    pub fn input_item_GetName(p_i: *mut input_item_t) -> *mut ::std::os::raw::c_char;
}
extern "C" {
    pub fn input_item_GetTitleFbName(p_i: *mut input_item_t) -> *mut ::std::os::raw::c_char;
}
extern "C" {
    pub fn input_item_GetURI(p_i: *mut input_item_t) -> *mut ::std::os::raw::c_char;
}
extern "C" {
    pub fn input_item_GetNowPlayingFb(p_item: *mut input_item_t) -> *mut ::std::os::raw::c_char;
}
extern "C" {
    pub fn input_item_SetURI(p_i: *mut input_item_t, psz_uri: *const ::std::os::raw::c_char);
}
extern "C" {
    pub fn input_item_GetDuration(p_i: *mut input_item_t) -> vlc_tick_t;
}
extern "C" {
    pub fn input_item_SetDuration(p_i: *mut input_item_t, i_duration: vlc_tick_t);
}
extern "C" {
    pub fn input_item_IsPreparsed(p_i: *mut input_item_t) -> bool;
}
extern "C" {
    pub fn input_item_IsArtFetched(p_i: *mut input_item_t) -> bool;
}
extern "C" {
    pub fn input_item_GetMetaExtra(
        p_i: *mut input_item_t,
        psz_name: *const ::std::os::raw::c_char,
    ) -> *mut ::std::os::raw::c_char;
}
extern "C" {
    pub fn input_item_GetMetaExtraNames(
        p_i: *mut input_item_t,
        pppsz_names: *mut *mut *mut ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_uint;
}
extern "C" {
    pub fn input_item_SetMetaExtra(
        p_i: *mut input_item_t,
        psz_name: *const ::std::os::raw::c_char,
        psz_value: *const ::std::os::raw::c_char,
    );
}

macro_rules! input_meta {
    ($set_fn:ident, $get_fn:ident, $meta_type:expr) => {
        #[inline]
        pub unsafe fn $set_fn(p_input: *mut input_item_t, val: *const ::std::os::raw::c_char) {
            unsafe { input_item_SetMeta(p_input, $meta_type, val) };
        }

        #[inline]
        pub unsafe fn $get_fn(p_input: *mut input_item_t) -> *mut ::std::os::raw::c_char {
            unsafe { input_item_GetMeta(p_input, $meta_type) }
        }
    };
}

input_meta!(input_item_SetTitle, input_item_GetTitle, vlc_meta_type_t::vlc_meta_Title);
input_meta!(input_item_SetArtist, input_item_GetArtist, vlc_meta_type_t::vlc_meta_Artist);
input_meta!(input_item_SetAlbumArtist, input_item_GetAlbumArtist, vlc_meta_type_t::vlc_meta_AlbumArtist);
input_meta!(input_item_SetGenre, input_item_GetGenre, vlc_meta_type_t::vlc_meta_Genre);
input_meta!(input_item_SetCopyright, input_item_GetCopyright, vlc_meta_type_t::vlc_meta_Copyright);
input_meta!(input_item_SetAlbum, input_item_GetAlbum, vlc_meta_type_t::vlc_meta_Album);
input_meta!(input_item_SetTrackNumber, input_item_GetTrackNumber, vlc_meta_type_t::vlc_meta_TrackNumber);
input_meta!(input_item_SetDescription, input_item_GetDescription, vlc_meta_type_t::vlc_meta_Description);
input_meta!(input_item_SetRating, input_item_GetRating, vlc_meta_type_t::vlc_meta_Rating);
input_meta!(input_item_SetDate, input_item_GetDate, vlc_meta_type_t::vlc_meta_Date);
input_meta!(input_item_SetSetting, input_item_GetSetting, vlc_meta_type_t::vlc_meta_Setting);
input_meta!(input_item_SetURL, input_item_GetURL, vlc_meta_type_t::vlc_meta_URL);
input_meta!(input_item_SetLanguage, input_item_GetLanguage, vlc_meta_type_t::vlc_meta_Language);
input_meta!(input_item_SetNowPlaying, input_item_GetNowPlaying, vlc_meta_type_t::vlc_meta_NowPlaying);
input_meta!(input_item_SetESNowPlaying, input_item_GetESNowPlaying, vlc_meta_type_t::vlc_meta_ESNowPlaying);
input_meta!(input_item_SetPublisher, input_item_GetPublisher, vlc_meta_type_t::vlc_meta_Publisher);
input_meta!(input_item_SetEncodedBy, input_item_GetEncodedBy, vlc_meta_type_t::vlc_meta_EncodedBy);
input_meta!(input_item_SetArtworkURL, input_item_GetArtworkURL, vlc_meta_type_t::vlc_meta_ArtworkURL);
input_meta!(input_item_SetTrackID, input_item_GetTrackID, vlc_meta_type_t::vlc_meta_TrackID);
input_meta!(input_item_SetTrackTotal, input_item_GetTrackTotal, vlc_meta_type_t::vlc_meta_TrackTotal);
input_meta!(input_item_SetDirector, input_item_GetDirector, vlc_meta_type_t::vlc_meta_Director);
input_meta!(input_item_SetSeason, input_item_GetSeason, vlc_meta_type_t::vlc_meta_Season);
input_meta!(input_item_SetEpisode, input_item_GetEpisode, vlc_meta_type_t::vlc_meta_Episode);
input_meta!(input_item_SetShowName, input_item_GetShowName, vlc_meta_type_t::vlc_meta_ShowName);
input_meta!(input_item_SetActors, input_item_GetActors, vlc_meta_type_t::vlc_meta_Actors);
input_meta!(input_item_SetDiscNumber, input_item_GetDiscNumber, vlc_meta_type_t::vlc_meta_DiscNumber);
input_meta!(input_item_SetDiscTotal, input_item_GetDiscTotal, vlc_meta_type_t::vlc_meta_DiscTotal);

extern "C" {
    pub fn input_item_GetInfo(
        p_i: *mut input_item_t,
        psz_cat: *const ::std::os::raw::c_char,
        psz_name: *const ::std::os::raw::c_char,
    ) -> *mut ::std::os::raw::c_char;
}
extern "C" {
    pub fn input_item_GetInfoLocked(
        p_i: *mut input_item_t,
        psz_cat: *const ::std::os::raw::c_char,
        psz_name: *const ::std::os::raw::c_char,
    ) -> *mut ::std::os::raw::c_char;
}
extern "C" {
    pub fn input_item_AddInfo(
        p_i: *mut input_item_t,
        psz_cat: *const ::std::os::raw::c_char,
        psz_name: *const ::std::os::raw::c_char,
        psz_format: *const ::std::os::raw::c_char,
        ...
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn input_item_DelInfo(
        p_i: *mut input_item_t,
        psz_cat: *const ::std::os::raw::c_char,
        psz_name: *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn input_item_ReplaceInfos(arg1: *mut input_item_t, arg2: *mut info_category_t);
}
extern "C" {
    pub fn input_item_MergeInfos(arg1: *mut input_item_t, arg2: *mut info_category_t);
}
extern "C" {
    pub fn input_item_NewExt(
        psz_uri: *const ::std::os::raw::c_char,
        psz_name: *const ::std::os::raw::c_char,
        i_duration: vlc_tick_t,
        i_type: input_item_type_e,
        i_net: input_item_net_type,
    ) -> *mut input_item_t;
}
extern "C" {
    pub fn input_item_Copy(arg1: *mut input_item_t) -> *mut input_item_t;
}
extern "C" {
    pub fn input_item_Hold(arg1: *mut input_item_t) -> *mut input_item_t;
}
extern "C" {
    pub fn input_item_Release(arg1: *mut input_item_t);
}
extern "C" {
    pub fn input_item_CreateFilename(
        arg1: *mut input_item_t,
        psz_path: *const ::std::os::raw::c_char,
        psz_prefix: *const ::std::os::raw::c_char,
        psz_extension: *const ::std::os::raw::c_char,
    ) -> *mut ::std::os::raw::c_char;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct input_item_parser_id_t {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct input_item_parser_cbs_t {
    pub on_ended: ::std::option::Option<
        unsafe extern "C" fn(
            item: *mut input_item_t,
            status: ::std::os::raw::c_int,
            userdata: *mut ::std::os::raw::c_void,
        ),
    >,
    pub on_subtree_added: ::std::option::Option<
        unsafe extern "C" fn(
            item: *mut input_item_t,
            subtree: *mut input_item_node_t,
            userdata: *mut ::std::os::raw::c_void,
        ),
    >,
    pub on_attachments_added: ::std::option::Option<
        unsafe extern "C" fn(
            item: *mut input_item_t,
            array: *const *mut input_attachment_t,
            count: usize,
            userdata: *mut ::std::os::raw::c_void,
        ),
    >,
}
extern "C" {
    pub fn input_item_Parse(
        item: *mut input_item_t,
        parent: *mut vlc_object_t,
        cbs: *const input_item_parser_cbs_t,
        userdata: *mut ::std::os::raw::c_void,
    ) -> *mut input_item_parser_id_t;
}
extern "C" {
    pub fn input_item_parser_id_Interrupt(parser: *mut input_item_parser_id_t);
}
extern "C" {
    pub fn input_item_parser_id_Release(parser: *mut input_item_parser_id_t);
}
#[repr(u32)]
#[non_exhaustive]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum input_item_meta_request_option_t {
    META_REQUEST_OPTION_NONE = 0,
    META_REQUEST_OPTION_SCOPE_LOCAL = 1,
    META_REQUEST_OPTION_SCOPE_NETWORK = 2,
    META_REQUEST_OPTION_SCOPE_ANY = 3,
    META_REQUEST_OPTION_SCOPE_FORCED = 4,
    META_REQUEST_OPTION_FETCH_LOCAL = 8,
    META_REQUEST_OPTION_FETCH_NETWORK = 16,
    META_REQUEST_OPTION_FETCH_ANY = 24,
    META_REQUEST_OPTION_DO_INTERACT = 32,
}
#[repr(u32)]
#[non_exhaustive]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum input_item_preparse_status {
    ITEM_PREPARSE_SKIPPED = 0,
    ITEM_PREPARSE_FAILED = 1,
    ITEM_PREPARSE_TIMEOUT = 2,
    ITEM_PREPARSE_DONE = 3,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct input_stats_t {
    pub i_read_packets: u64,
    pub i_read_bytes: u64,
    pub f_input_bitrate: f32,
    pub i_demux_read_packets: u64,
    pub i_demux_read_bytes: u64,
    pub f_demux_bitrate: f32,
    pub i_demux_corrupted: u64,
    pub i_demux_discontinuity: u64,
    pub i_decoded_audio: u64,
    pub i_decoded_video: u64,
    pub i_displayed_pictures: u64,
    pub i_late_pictures: u64,
    pub i_lost_pictures: u64,
    pub i_played_abuffers: u64,
    pub i_lost_abuffers: u64,
}
