/* automatically generated by rust-bindgen 0.66.1 */

#![allow(rustdoc::bare_urls)]
#![allow(rustdoc::broken_intra_doc_links)]
#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]

use crate::playlist::sys::vlc_playlist_t;

#[allow(non_camel_case_types)]
#[allow(unused)]
extern {
    pub type intf_thread_t;
}

extern "C" {
    pub fn vlc_intf_GetMainPlaylist(intf: *mut intf_thread_t) -> *mut vlc_playlist_t;
}
