/* automatically generated by rust-bindgen 0.66.1 */

#![allow(rustdoc::bare_urls)]
#![allow(rustdoc::broken_intra_doc_links)]
#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]

pub const VLC_SUCCESS: u32 = 0;
pub const VLC_ENOMEM: i32 = -12;
pub const VLC_ETIMEOUT: i32 = -110;
pub const VLC_ENOENT: i32 = -2;
pub const VLC_EINVAL: i32 = -22;
pub const VLC_EACCES: i32 = -13;
pub const VLC_ENOTSUP: i32 = -95;

pub const VLC_RUST_EGENERIC: ::std::os::raw::c_int = -2147483648;
