/* automatically generated by rust-bindgen 0.66.1 */

#![allow(rustdoc::bare_urls)]
#![allow(rustdoc::broken_intra_doc_links)]
#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]

#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct vlc_url_t {
    pub psz_protocol: *mut ::std::os::raw::c_char,
    pub psz_username: *mut ::std::os::raw::c_char,
    pub psz_password: *mut ::std::os::raw::c_char,
    pub psz_host: *mut ::std::os::raw::c_char,
    pub i_port: ::std::os::raw::c_uint,
    pub psz_path: *mut ::std::os::raw::c_char,
    pub psz_option: *mut ::std::os::raw::c_char,
    pub psz_fragment: *mut ::std::os::raw::c_char,
    pub psz_buffer: *mut ::std::os::raw::c_char,
    pub psz_pathbuffer: *mut ::std::os::raw::c_char,
}

extern "C" {
    pub fn vlc_UrlParse(
        url: *mut vlc_url_t,
        str_: *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;

    pub fn vlc_UrlParseFixup(
        url: *mut vlc_url_t,
        str_: *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;

    pub fn vlc_UrlClean(arg1: *mut vlc_url_t);
}
