/* automatically generated by rust-bindgen 0.66.1 */

#![allow(rustdoc::bare_urls)]
#![allow(rustdoc::broken_intra_doc_links)]
#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]

#[repr(C)]
#[derive(Copy, Clone, Debug, Default, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub struct __BindgenBitfieldUnit<Storage> {
    storage: Storage,
}
impl<Storage> __BindgenBitfieldUnit<Storage> {
    #[inline]
    pub const fn new(storage: Storage) -> Self {
        Self { storage }
    }
}
impl<Storage> __BindgenBitfieldUnit<Storage>
where
    Storage: AsRef<[u8]> + AsMut<[u8]>,
{
    #[inline]
    pub fn get_bit(&self, index: usize) -> bool {
        debug_assert!(index / 8 < self.storage.as_ref().len());
        let byte_index = index / 8;
        let byte = self.storage.as_ref()[byte_index];
        let bit_index = if cfg!(target_endian = "big") {
            7 - (index % 8)
        } else {
            index % 8
        };
        let mask = 1 << bit_index;
        byte & mask == mask
    }
    #[inline]
    pub fn set_bit(&mut self, index: usize, val: bool) {
        debug_assert!(index / 8 < self.storage.as_ref().len());
        let byte_index = index / 8;
        let byte = &mut self.storage.as_mut()[byte_index];
        let bit_index = if cfg!(target_endian = "big") {
            7 - (index % 8)
        } else {
            index % 8
        };
        let mask = 1 << bit_index;
        if val {
            *byte |= mask;
        } else {
            *byte &= !mask;
        }
    }
    #[inline]
    pub fn get(&self, bit_offset: usize, bit_width: u8) -> u64 {
        debug_assert!(bit_width <= 64);
        debug_assert!(bit_offset / 8 < self.storage.as_ref().len());
        debug_assert!((bit_offset + (bit_width as usize)) / 8 <= self.storage.as_ref().len());
        let mut val = 0;
        for i in 0..(bit_width as usize) {
            if self.get_bit(i + bit_offset) {
                let index = if cfg!(target_endian = "big") {
                    bit_width as usize - 1 - i
                } else {
                    i
                };
                val |= 1 << index;
            }
        }
        val
    }
    #[inline]
    pub fn set(&mut self, bit_offset: usize, bit_width: u8, val: u64) {
        debug_assert!(bit_width <= 64);
        debug_assert!(bit_offset / 8 < self.storage.as_ref().len());
        debug_assert!((bit_offset + (bit_width as usize)) / 8 <= self.storage.as_ref().len());
        for i in 0..(bit_width as usize) {
            let mask = 1 << i;
            let val_bit_is_set = val & mask == mask;
            let index = if cfg!(target_endian = "big") {
                bit_width as usize - 1 - i
            } else {
                i
            };
            self.set_bit(index + bit_offset, val_bit_is_set);
        }
    }
}
pub type vlc_fourcc_t = u32;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct vlc_viewpoint_t {
    pub yaw: f32,
    pub pitch: f32,
    pub roll: f32,
    pub fov: f32,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct video_palette_t {
    pub i_entries: ::std::os::raw::c_int,
    pub palette: [[u8; 4usize]; 256usize],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct audio_replay_gain_t {
    pub pb_peak: [bool; 2usize],
    pub pf_peak: [f32; 2usize],
    pub pb_gain: [bool; 2usize],
    pub pf_gain: [f32; 2usize],
}
#[repr(u32)]
#[non_exhaustive]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum audio_channel_type_t {
    AUDIO_CHANNEL_TYPE_BITMAP = 0,
    AUDIO_CHANNEL_TYPE_AMBISONICS = 1,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct audio_format_t {
    pub i_format: vlc_fourcc_t,
    pub i_rate: ::std::os::raw::c_uint,
    pub i_physical_channels: u16,
    pub i_chan_mode: u16,
    pub channel_type: audio_channel_type_t,
    pub i_bytes_per_frame: ::std::os::raw::c_uint,
    pub i_frame_length: ::std::os::raw::c_uint,
    pub i_bitspersample: ::std::os::raw::c_uint,
    pub i_blockalign: ::std::os::raw::c_uint,
    pub i_channels: u8,
}
impl video_orientation_t {
    pub const ORIENT_NORMAL: video_orientation_t = video_orientation_t::ORIENT_TOP_LEFT;
}
impl video_orientation_t {
    pub const ORIENT_TRANSPOSED: video_orientation_t = video_orientation_t::ORIENT_LEFT_TOP;
}
impl video_orientation_t {
    pub const ORIENT_ANTI_TRANSPOSED: video_orientation_t =
        video_orientation_t::ORIENT_RIGHT_BOTTOM;
}
impl video_orientation_t {
    pub const ORIENT_HFLIPPED: video_orientation_t = video_orientation_t::ORIENT_TOP_RIGHT;
}
impl video_orientation_t {
    pub const ORIENT_VFLIPPED: video_orientation_t = video_orientation_t::ORIENT_BOTTOM_LEFT;
}
impl video_orientation_t {
    pub const ORIENT_ROTATED_180: video_orientation_t = video_orientation_t::ORIENT_BOTTOM_RIGHT;
}
impl video_orientation_t {
    pub const ORIENT_ROTATED_270: video_orientation_t = video_orientation_t::ORIENT_LEFT_BOTTOM;
}
impl video_orientation_t {
    pub const ORIENT_ROTATED_90: video_orientation_t = video_orientation_t::ORIENT_RIGHT_TOP;
}
#[repr(u32)]
#[non_exhaustive]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum video_orientation_t {
    ORIENT_TOP_LEFT = 0,
    ORIENT_TOP_RIGHT = 1,
    ORIENT_BOTTOM_LEFT = 2,
    ORIENT_BOTTOM_RIGHT = 3,
    ORIENT_LEFT_TOP = 4,
    ORIENT_LEFT_BOTTOM = 5,
    ORIENT_RIGHT_TOP = 6,
    ORIENT_RIGHT_BOTTOM = 7,
}
#[repr(u32)]
#[non_exhaustive]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum video_multiview_mode_t {
    MULTIVIEW_2D = 0,
    MULTIVIEW_STEREO_SBS = 1,
    MULTIVIEW_STEREO_TB = 2,
    MULTIVIEW_STEREO_ROW = 3,
    MULTIVIEW_STEREO_COL = 4,
    MULTIVIEW_STEREO_FRAME = 5,
    MULTIVIEW_STEREO_CHECKERBOARD = 6,
}
#[repr(u32)]
#[non_exhaustive]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum video_projection_mode_t {
    PROJECTION_MODE_RECTANGULAR = 0,
    PROJECTION_MODE_EQUIRECTANGULAR = 1,
    PROJECTION_MODE_CUBEMAP_LAYOUT_STANDARD = 256,
}
#[repr(u32)]
#[non_exhaustive]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum video_color_primaries_t {
    COLOR_PRIMARIES_UNDEF = 0,
    COLOR_PRIMARIES_BT601_525 = 1,
    COLOR_PRIMARIES_BT601_625 = 2,
    COLOR_PRIMARIES_BT709 = 3,
    COLOR_PRIMARIES_BT2020 = 4,
    COLOR_PRIMARIES_DCI_P3 = 5,
    COLOR_PRIMARIES_FCC1953 = 6,
}
#[repr(u32)]
#[non_exhaustive]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum video_transfer_func_t {
    TRANSFER_FUNC_UNDEF = 0,
    TRANSFER_FUNC_LINEAR = 1,
    TRANSFER_FUNC_SRGB = 2,
    TRANSFER_FUNC_BT470_BG = 3,
    TRANSFER_FUNC_BT470_M = 4,
    TRANSFER_FUNC_BT709 = 5,
    TRANSFER_FUNC_SMPTE_ST2084 = 6,
    TRANSFER_FUNC_SMPTE_240 = 7,
    TRANSFER_FUNC_HLG = 8,
}
#[repr(u32)]
#[non_exhaustive]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum video_color_space_t {
    COLOR_SPACE_UNDEF = 0,
    COLOR_SPACE_BT601 = 1,
    COLOR_SPACE_BT709 = 2,
    COLOR_SPACE_BT2020 = 3,
}
#[repr(u32)]
#[non_exhaustive]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum video_chroma_location_t {
    CHROMA_LOCATION_UNDEF = 0,
    CHROMA_LOCATION_LEFT = 1,
    CHROMA_LOCATION_CENTER = 2,
    CHROMA_LOCATION_TOP_LEFT = 3,
    CHROMA_LOCATION_TOP_CENTER = 4,
    CHROMA_LOCATION_BOTTOM_LEFT = 5,
    CHROMA_LOCATION_BOTTOM_CENTER = 6,
}
#[repr(u32)]
#[non_exhaustive]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum video_color_range_t {
    COLOR_RANGE_UNDEF = 0,
    COLOR_RANGE_FULL = 1,
    COLOR_RANGE_LIMITED = 2,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct video_format_t {
    pub i_chroma: vlc_fourcc_t,
    pub i_width: ::std::os::raw::c_uint,
    pub i_height: ::std::os::raw::c_uint,
    pub i_x_offset: ::std::os::raw::c_uint,
    pub i_y_offset: ::std::os::raw::c_uint,
    pub i_visible_width: ::std::os::raw::c_uint,
    pub i_visible_height: ::std::os::raw::c_uint,
    pub i_sar_num: ::std::os::raw::c_uint,
    pub i_sar_den: ::std::os::raw::c_uint,
    pub i_frame_rate: ::std::os::raw::c_uint,
    pub i_frame_rate_base: ::std::os::raw::c_uint,
    pub p_palette: *mut video_palette_t,
    pub orientation: video_orientation_t,
    pub primaries: video_color_primaries_t,
    pub transfer: video_transfer_func_t,
    pub space: video_color_space_t,
    pub color_range: video_color_range_t,
    pub chroma_location: video_chroma_location_t,
    pub multiview_mode: video_multiview_mode_t,
    pub b_multiview_right_eye_first: bool,
    pub projection_mode: video_projection_mode_t,
    pub pose: vlc_viewpoint_t,
    pub mastering: video_format_t__bindgen_ty_1,
    pub lighting: video_format_t__bindgen_ty_2,
    pub dovi: video_format_t__bindgen_ty_3,
    pub i_cubemap_padding: u32,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct video_format_t__bindgen_ty_1 {
    pub primaries: [u16; 6usize],
    pub white_point: [u16; 2usize],
    pub max_luminance: u32,
    pub min_luminance: u32,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct video_format_t__bindgen_ty_2 {
    pub MaxCLL: u16,
    pub MaxFALL: u16,
}
#[repr(C)]
#[repr(align(4))]
#[derive(Debug, Copy, Clone)]
pub struct video_format_t__bindgen_ty_3 {
    pub version_major: u8,
    pub version_minor: u8,
    pub _bitfield_align_1: [u8; 0],
    pub _bitfield_1: __BindgenBitfieldUnit<[u8; 2usize]>,
}
impl video_format_t__bindgen_ty_3 {
    #[inline]
    pub fn profile(&self) -> ::std::os::raw::c_uint {
        unsafe { ::std::mem::transmute(self._bitfield_1.get(0usize, 7u8) as u32) }
    }
    #[inline]
    pub fn set_profile(&mut self, val: ::std::os::raw::c_uint) {
        unsafe {
            let val: u32 = ::std::mem::transmute(val);
            self._bitfield_1.set(0usize, 7u8, val as u64)
        }
    }
    #[inline]
    pub fn level(&self) -> ::std::os::raw::c_uint {
        unsafe { ::std::mem::transmute(self._bitfield_1.get(7usize, 6u8) as u32) }
    }
    #[inline]
    pub fn set_level(&mut self, val: ::std::os::raw::c_uint) {
        unsafe {
            let val: u32 = ::std::mem::transmute(val);
            self._bitfield_1.set(7usize, 6u8, val as u64)
        }
    }
    #[inline]
    pub fn rpu_present(&self) -> ::std::os::raw::c_uint {
        unsafe { ::std::mem::transmute(self._bitfield_1.get(13usize, 1u8) as u32) }
    }
    #[inline]
    pub fn set_rpu_present(&mut self, val: ::std::os::raw::c_uint) {
        unsafe {
            let val: u32 = ::std::mem::transmute(val);
            self._bitfield_1.set(13usize, 1u8, val as u64)
        }
    }
    #[inline]
    pub fn el_present(&self) -> ::std::os::raw::c_uint {
        unsafe { ::std::mem::transmute(self._bitfield_1.get(14usize, 1u8) as u32) }
    }
    #[inline]
    pub fn set_el_present(&mut self, val: ::std::os::raw::c_uint) {
        unsafe {
            let val: u32 = ::std::mem::transmute(val);
            self._bitfield_1.set(14usize, 1u8, val as u64)
        }
    }
    #[inline]
    pub fn bl_present(&self) -> ::std::os::raw::c_uint {
        unsafe { ::std::mem::transmute(self._bitfield_1.get(15usize, 1u8) as u32) }
    }
    #[inline]
    pub fn set_bl_present(&mut self, val: ::std::os::raw::c_uint) {
        unsafe {
            let val: u32 = ::std::mem::transmute(val);
            self._bitfield_1.set(15usize, 1u8, val as u64)
        }
    }
    #[inline]
    pub fn new_bitfield_1(
        profile: ::std::os::raw::c_uint,
        level: ::std::os::raw::c_uint,
        rpu_present: ::std::os::raw::c_uint,
        el_present: ::std::os::raw::c_uint,
        bl_present: ::std::os::raw::c_uint,
    ) -> __BindgenBitfieldUnit<[u8; 2usize]> {
        let mut __bindgen_bitfield_unit: __BindgenBitfieldUnit<[u8; 2usize]> = Default::default();
        __bindgen_bitfield_unit.set(0usize, 7u8, {
            let profile: u32 = unsafe { ::std::mem::transmute(profile) };
            profile as u64
        });
        __bindgen_bitfield_unit.set(7usize, 6u8, {
            let level: u32 = unsafe { ::std::mem::transmute(level) };
            level as u64
        });
        __bindgen_bitfield_unit.set(13usize, 1u8, {
            let rpu_present: u32 = unsafe { ::std::mem::transmute(rpu_present) };
            rpu_present as u64
        });
        __bindgen_bitfield_unit.set(14usize, 1u8, {
            let el_present: u32 = unsafe { ::std::mem::transmute(el_present) };
            el_present as u64
        });
        __bindgen_bitfield_unit.set(15usize, 1u8, {
            let bl_present: u32 = unsafe { ::std::mem::transmute(bl_present) };
            bl_present as u64
        });
        __bindgen_bitfield_unit
    }
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct subs_format_t {
    pub psz_encoding: *mut ::std::os::raw::c_char,
    pub i_x_origin: ::std::os::raw::c_int,
    pub i_y_origin: ::std::os::raw::c_int,
    pub spu: subs_format_t__bindgen_ty_1,
    pub dvb: subs_format_t__bindgen_ty_2,
    pub teletext: subs_format_t__bindgen_ty_3,
    pub cc: subs_format_t__bindgen_ty_4,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct subs_format_t__bindgen_ty_1 {
    pub i_original_frame_width: ::std::os::raw::c_uint,
    pub i_original_frame_height: ::std::os::raw::c_uint,
    pub palette: [u32; 16usize],
    pub b_palette: bool,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct subs_format_t__bindgen_ty_2 {
    pub i_id: ::std::os::raw::c_int,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct subs_format_t__bindgen_ty_3 {
    pub i_magazine: u8,
    pub i_page: u8,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct subs_format_t__bindgen_ty_4 {
    pub i_channel: u8,
    pub i_reorder_depth: ::std::os::raw::c_int,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct extra_languages_t {
    pub psz_language: *mut ::std::os::raw::c_char,
    pub psz_description: *mut ::std::os::raw::c_char,
}
#[repr(u32)]
#[non_exhaustive]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum es_format_category_e {
    UNKNOWN_ES = 0,
    VIDEO_ES = 1,
    AUDIO_ES = 2,
    SPU_ES = 3,
    DATA_ES = 4,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub struct es_format_t {
    pub i_cat: es_format_category_e,
    pub i_codec: vlc_fourcc_t,
    pub i_original_fourcc: vlc_fourcc_t,
    pub i_id: ::std::os::raw::c_int,
    pub i_group: ::std::os::raw::c_int,
    pub i_priority: ::std::os::raw::c_int,
    pub psz_language: *mut ::std::os::raw::c_char,
    pub psz_description: *mut ::std::os::raw::c_char,
    pub i_extra_languages: ::std::os::raw::c_uint,
    pub p_extra_languages: *mut extra_languages_t,
    pub __bindgen_anon_1: es_format_t__bindgen_ty_1,
    pub i_bitrate: ::std::os::raw::c_uint,
    pub i_profile: ::std::os::raw::c_int,
    pub i_level: ::std::os::raw::c_int,
    pub b_packetized: bool,
    pub i_extra: ::std::os::raw::c_int,
    pub p_extra: *mut ::std::os::raw::c_void,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub union es_format_t__bindgen_ty_1 {
    pub __bindgen_anon_1: es_format_t__bindgen_ty_1__bindgen_ty_1,
    pub video: video_format_t,
    pub subs: subs_format_t,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct es_format_t__bindgen_ty_1__bindgen_ty_1 {
    pub audio: audio_format_t,
    pub audio_replay_gain: audio_replay_gain_t,
}
