[workspace]
resolver = "2"
members = ["wasm-rs"]

[workspace.dependencies]
vlcrs-core = { path = "../src/rust/vlcrs-core" }
vlcrs-macros = { path = "../src/rust/vlcrs-macros" }
vlcrs-messages = { path = "../src/rust/vlcrs-messages" }
vlcrs-plugin = { path = "../src/rust/vlcrs-plugin" }
vlcrs-utils = { path = "../src/rust/vlcrs-utils" }
