/* automatically generated by rust-bindgen 0.66.1 */

#![allow(rustdoc::bare_urls)]
#![allow(rustdoc::broken_intra_doc_links)]
#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]

use crate::tick::sys::vlc_tick_t;

pub type atomic_uint = u32;
pub type atomic_ulong = u64;
#[repr(C)]
#[derive(Copy, Clone)]
pub struct vlc_mutex_t {
    pub __bindgen_anon_1: vlc_mutex_t__bindgen_ty_1,
}

#[repr(C)]
#[derive(Copy, Clone)]
pub union vlc_mutex_t__bindgen_ty_1 {
    pub __bindgen_anon_1: vlc_mutex_t__bindgen_ty_1__bindgen_ty_1,
    pub dummy: vlc_mutex_t__bindgen_ty_1__bindgen_ty_2,
}

#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct vlc_mutex_t__bindgen_ty_1__bindgen_ty_1 {
    pub value: atomic_uint,
    pub recursion: atomic_uint,
    pub owner: atomic_ulong,
}

#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct vlc_mutex_t__bindgen_ty_1__bindgen_ty_2 {
    pub value: ::std::os::raw::c_uint,
    pub recursion: ::std::os::raw::c_uint,
    pub owner: ::std::os::raw::c_ulong,
}

extern "C" {
    pub fn vlc_mutex_init(arg1: *mut vlc_mutex_t);

    pub fn vlc_mutex_lock(arg1: *mut vlc_mutex_t);

    pub fn vlc_mutex_unlock(arg1: *mut vlc_mutex_t);

    pub fn vlc_tick_now() -> vlc_tick_t;

    pub fn vlc_tick_wait(deadline: vlc_tick_t);

    pub fn vlc_tick_sleep(delay: vlc_tick_t);
}

