/* automatically generated by rust-bindgen 0.66.1 */

#![allow(rustdoc::bare_urls)]
#![allow(rustdoc::broken_intra_doc_links)]
#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]

use crate::input_item::sys::input_item_t;
use crate::object::sys::vlc_object_t;
use crate::player::sys::vlc_player_t;

#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct vlc_playlist {
    _unused: [u8; 0],
}
pub type vlc_playlist_t = vlc_playlist;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct vlc_playlist_item {
    _unused: [u8; 0],
}
pub type vlc_playlist_item_t = vlc_playlist_item;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct vlc_playlist_listener_id {
    _unused: [u8; 0],
}
#[repr(u32)]
#[non_exhaustive]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum vlc_playlist_playback_repeat {
    VLC_PLAYLIST_PLAYBACK_REPEAT_NONE = 0,
    VLC_PLAYLIST_PLAYBACK_REPEAT_CURRENT = 1,
    VLC_PLAYLIST_PLAYBACK_REPEAT_ALL = 2,
}
#[repr(u32)]
#[non_exhaustive]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum vlc_playlist_playback_order {
    VLC_PLAYLIST_PLAYBACK_ORDER_NORMAL = 0,
    VLC_PLAYLIST_PLAYBACK_ORDER_RANDOM = 1,
}
#[repr(u32)]
#[non_exhaustive]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum vlc_playlist_sort_key {
    VLC_PLAYLIST_SORT_KEY_TITLE = 0,
    VLC_PLAYLIST_SORT_KEY_DURATION = 1,
    VLC_PLAYLIST_SORT_KEY_ARTIST = 2,
    VLC_PLAYLIST_SORT_KEY_ALBUM = 3,
    VLC_PLAYLIST_SORT_KEY_ALBUM_ARTIST = 4,
    VLC_PLAYLIST_SORT_KEY_GENRE = 5,
    VLC_PLAYLIST_SORT_KEY_DATE = 6,
    VLC_PLAYLIST_SORT_KEY_TRACK_NUMBER = 7,
    VLC_PLAYLIST_SORT_KEY_DISC_NUMBER = 8,
    VLC_PLAYLIST_SORT_KEY_URL = 9,
    VLC_PLAYLIST_SORT_KEY_RATING = 10,
    VLC_PLAYLIST_SORT_KEY_FILE_SIZE = 11,
    VLC_PLAYLIST_SORT_KEY_FILE_MODIFIED = 12,
}
#[repr(u32)]
#[non_exhaustive]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum vlc_playlist_sort_order {
    VLC_PLAYLIST_SORT_ORDER_ASCENDING = 0,
    VLC_PLAYLIST_SORT_ORDER_DESCENDING = 1,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct vlc_playlist_sort_criterion {
    pub key: vlc_playlist_sort_key,
    pub order: vlc_playlist_sort_order,
}
#[repr(u32)]
#[non_exhaustive]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum vlc_playlist_media_stopped_action {
    VLC_PLAYLIST_MEDIA_STOPPED_CONTINUE = 0,
    VLC_PLAYLIST_MEDIA_STOPPED_PAUSE = 1,
    VLC_PLAYLIST_MEDIA_STOPPED_STOP = 2,
    VLC_PLAYLIST_MEDIA_STOPPED_EXIT = 3,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct vlc_playlist_callbacks {
    pub on_items_reset: ::std::option::Option<
        unsafe extern "C" fn(
            arg1: *mut vlc_playlist_t,
            items: *const *mut vlc_playlist_item_t,
            count: usize,
            userdata: *mut ::std::os::raw::c_void,
        ),
    >,
    pub on_items_added: ::std::option::Option<
        unsafe extern "C" fn(
            playlist: *mut vlc_playlist_t,
            index: usize,
            items: *const *mut vlc_playlist_item_t,
            count: usize,
            userdata: *mut ::std::os::raw::c_void,
        ),
    >,
    pub on_items_moved: ::std::option::Option<
        unsafe extern "C" fn(
            playlist: *mut vlc_playlist_t,
            index: usize,
            count: usize,
            target: usize,
            userdata: *mut ::std::os::raw::c_void,
        ),
    >,
    pub on_items_removed: ::std::option::Option<
        unsafe extern "C" fn(
            playlist: *mut vlc_playlist_t,
            index: usize,
            count: usize,
            userdata: *mut ::std::os::raw::c_void,
        ),
    >,
    pub on_items_updated: ::std::option::Option<
        unsafe extern "C" fn(
            playlist: *mut vlc_playlist_t,
            index: usize,
            items: *const *mut vlc_playlist_item_t,
            count: usize,
            userdata: *mut ::std::os::raw::c_void,
        ),
    >,
    pub on_playback_repeat_changed: ::std::option::Option<
        unsafe extern "C" fn(
            playlist: *mut vlc_playlist_t,
            repeat: vlc_playlist_playback_repeat,
            userdata: *mut ::std::os::raw::c_void,
        ),
    >,
    pub on_playback_order_changed: ::std::option::Option<
        unsafe extern "C" fn(
            playlist: *mut vlc_playlist_t,
            order: vlc_playlist_playback_order,
            userdata: *mut ::std::os::raw::c_void,
        ),
    >,
    pub on_current_index_changed: ::std::option::Option<
        unsafe extern "C" fn(
            playlist: *mut vlc_playlist_t,
            index: isize,
            userdata: *mut ::std::os::raw::c_void,
        ),
    >,
    pub on_has_prev_changed: ::std::option::Option<
        unsafe extern "C" fn(
            playlist: *mut vlc_playlist_t,
            has_prev: bool,
            userdata: *mut ::std::os::raw::c_void,
        ),
    >,
    pub on_has_next_changed: ::std::option::Option<
        unsafe extern "C" fn(
            playlist: *mut vlc_playlist_t,
            has_next: bool,
            userdata: *mut ::std::os::raw::c_void,
        ),
    >,
    pub on_media_stopped_action_changed: ::std::option::Option<
        unsafe extern "C" fn(
            playlist: *mut vlc_playlist_t,
            new_action: vlc_playlist_media_stopped_action,
            userdata: *mut ::std::os::raw::c_void,
        ),
    >,
}
extern "C" {
    pub fn vlc_playlist_item_Hold(arg1: *mut vlc_playlist_item_t);

    pub fn vlc_playlist_item_Release(arg1: *mut vlc_playlist_item_t);

    pub fn vlc_playlist_item_GetMedia(arg1: *mut vlc_playlist_item_t) -> *mut input_item_t;

    pub fn vlc_playlist_item_GetId(arg1: *mut vlc_playlist_item_t) -> u64;

    pub fn vlc_playlist_New(parent: *mut vlc_object_t) -> *mut vlc_playlist_t;

    pub fn vlc_playlist_Delete(arg1: *mut vlc_playlist_t);

    pub fn vlc_playlist_Lock(arg1: *mut vlc_playlist_t);

    pub fn vlc_playlist_Unlock(arg1: *mut vlc_playlist_t);

    pub fn vlc_playlist_AddListener(
        playlist: *mut vlc_playlist_t,
        cbs: *const vlc_playlist_callbacks,
        userdata: *mut ::std::os::raw::c_void,
        notify_current_state: bool,
    ) -> *mut vlc_playlist_listener_id;

    pub fn vlc_playlist_RemoveListener(
        playlist: *mut vlc_playlist_t,
        id: *mut vlc_playlist_listener_id,
    );

    pub fn vlc_playlist_SetMediaStoppedAction(
        playlist: *mut vlc_playlist_t,
        action: vlc_playlist_media_stopped_action,
    );

    pub fn vlc_playlist_Count(playlist: *mut vlc_playlist_t) -> usize;

    pub fn vlc_playlist_Get(
        playlist: *mut vlc_playlist_t,
        index: usize,
    ) -> *mut vlc_playlist_item_t;

    pub fn vlc_playlist_Clear(playlist: *mut vlc_playlist_t);

    pub fn vlc_playlist_Insert(
        playlist: *mut vlc_playlist_t,
        index: usize,
        media: *const *mut input_item_t,
        count: usize,
    ) -> ::std::os::raw::c_int;

    pub fn vlc_playlist_Move(
        playlist: *mut vlc_playlist_t,
        index: usize,
        count: usize,
        target: usize,
    );

    pub fn vlc_playlist_Remove(playlist: *mut vlc_playlist_t, index: usize, count: usize);

    pub fn vlc_playlist_RequestInsert(
        playlist: *mut vlc_playlist_t,
        index: usize,
        media: *const *mut input_item_t,
        count: usize,
    ) -> ::std::os::raw::c_int;

    pub fn vlc_playlist_RequestMove(
        playlist: *mut vlc_playlist_t,
        items: *const *mut vlc_playlist_item_t,
        count: usize,
        target: usize,
        index_hint: isize,
    ) -> ::std::os::raw::c_int;

    pub fn vlc_playlist_RequestRemove(
        playlist: *mut vlc_playlist_t,
        items: *const *mut vlc_playlist_item_t,
        count: usize,
        index_hint: isize,
    ) -> ::std::os::raw::c_int;

    pub fn vlc_playlist_Shuffle(playlist: *mut vlc_playlist_t);

    pub fn vlc_playlist_Sort(
        playlist: *mut vlc_playlist_t,
        criteria: *const vlc_playlist_sort_criterion,
        count: usize,
    ) -> ::std::os::raw::c_int;

    pub fn vlc_playlist_IndexOf(
        playlist: *mut vlc_playlist_t,
        item: *const vlc_playlist_item_t,
    ) -> isize;

    pub fn vlc_playlist_IndexOfMedia(
        playlist: *mut vlc_playlist_t,
        media: *const input_item_t,
    ) -> isize;

    pub fn vlc_playlist_IndexOfId(playlist: *mut vlc_playlist_t, id: u64) -> isize;

    pub fn vlc_playlist_GetPlaybackRepeat(
        playlist: *mut vlc_playlist_t,
    ) -> vlc_playlist_playback_repeat;

    pub fn vlc_playlist_GetPlaybackOrder(
        playlist: *mut vlc_playlist_t,
    ) -> vlc_playlist_playback_order;

    pub fn vlc_playlist_SetPlaybackRepeat(
        playlist: *mut vlc_playlist_t,
        repeat: vlc_playlist_playback_repeat,
    );

    pub fn vlc_playlist_SetPlaybackOrder(
        playlist: *mut vlc_playlist_t,
        order: vlc_playlist_playback_order,
    );

    pub fn vlc_playlist_GetCurrentIndex(playlist: *mut vlc_playlist_t) -> isize;

    pub fn vlc_playlist_HasPrev(playlist: *mut vlc_playlist_t) -> bool;

    pub fn vlc_playlist_HasNext(playlist: *mut vlc_playlist_t) -> bool;

    pub fn vlc_playlist_Prev(playlist: *mut vlc_playlist_t) -> ::std::os::raw::c_int;

    pub fn vlc_playlist_Next(playlist: *mut vlc_playlist_t) -> ::std::os::raw::c_int;

    pub fn vlc_playlist_GoTo(playlist: *mut vlc_playlist_t, index: isize) -> ::std::os::raw::c_int;

    pub fn vlc_playlist_RequestGoTo(
        playlist: *mut vlc_playlist_t,
        item: *mut vlc_playlist_item_t,
        index_hint: isize,
    ) -> ::std::os::raw::c_int;

    pub fn vlc_playlist_GetPlayer(playlist: *mut vlc_playlist_t) -> *mut vlc_player_t;

    pub fn vlc_playlist_Start(playlist: *mut vlc_playlist_t) -> ::std::os::raw::c_int;

    pub fn vlc_playlist_Stop(playlist: *mut vlc_playlist_t);

    pub fn vlc_playlist_Pause(playlist: *mut vlc_playlist_t);

    pub fn vlc_playlist_Resume(playlist: *mut vlc_playlist_t);

    pub fn vlc_playlist_Preparse(playlist: *mut vlc_playlist_t, media: *mut input_item_t);

    pub fn vlc_playlist_Export(
        playlist: *mut vlc_playlist_t,
        filename: *const ::std::os::raw::c_char,
        type_: *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}

