/* automatically generated by rust-bindgen 0.66.1 */

#![allow(rustdoc::bare_urls)]
#![allow(rustdoc::broken_intra_doc_links)]
#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]

#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct vlc_meta_t {
    _unused: [u8; 0],
}

#[repr(u32)]
#[non_exhaustive]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum vlc_meta_type_t {
    vlc_meta_Title = 0,
    vlc_meta_Artist = 1,
    vlc_meta_Genre = 2,
    vlc_meta_Copyright = 3,
    vlc_meta_Album = 4,
    vlc_meta_TrackNumber = 5,
    vlc_meta_Description = 6,
    vlc_meta_Rating = 7,
    vlc_meta_Date = 8,
    vlc_meta_Setting = 9,
    vlc_meta_URL = 10,
    vlc_meta_Language = 11,
    vlc_meta_NowPlaying = 12,
    vlc_meta_ESNowPlaying = 13,
    vlc_meta_Publisher = 14,
    vlc_meta_EncodedBy = 15,
    vlc_meta_ArtworkURL = 16,
    vlc_meta_TrackID = 17,
    vlc_meta_TrackTotal = 18,
    vlc_meta_Director = 19,
    vlc_meta_Season = 20,
    vlc_meta_Episode = 21,
    vlc_meta_ShowName = 22,
    vlc_meta_Actors = 23,
    vlc_meta_AlbumArtist = 24,
    vlc_meta_DiscNumber = 25,
    vlc_meta_DiscTotal = 26,
}
