/* automatically generated by rust-bindgen 0.66.1 */

#![allow(rustdoc::bare_urls)]
#![allow(rustdoc::broken_intra_doc_links)]
#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]

use crate::object::sys::vlc_object_t;

pub const VLC_VAR_TYPE: u32 = 255;
pub const VLC_VAR_CLASS: u32 = 240;
pub const VLC_VAR_FLAGS: u32 = 65280;
pub const VLC_VAR_VOID: u32 = 16;
pub const VLC_VAR_BOOL: u32 = 32;
pub const VLC_VAR_INTEGER: u32 = 48;
pub const VLC_VAR_STRING: u32 = 64;
pub const VLC_VAR_FLOAT: u32 = 80;
pub const VLC_VAR_ADDRESS: u32 = 112;
pub const VLC_VAR_COORDS: u32 = 160;
pub const VLC_VAR_HASCHOICE: u32 = 256;
pub const VLC_VAR_ISCOMMAND: u32 = 8192;
pub const VLC_VAR_DOINHERIT: u32 = 32768;
pub const VLC_VAR_SETSTEP: u32 = 18;
pub const VLC_VAR_SETVALUE: u32 = 19;
pub const VLC_VAR_SETTEXT: u32 = 20;
pub const VLC_VAR_GETTEXT: u32 = 21;
pub const VLC_VAR_GETMIN: u32 = 22;
pub const VLC_VAR_GETMAX: u32 = 23;
pub const VLC_VAR_GETSTEP: u32 = 24;
pub const VLC_VAR_ADDCHOICE: u32 = 32;
pub const VLC_VAR_DELCHOICE: u32 = 33;
pub const VLC_VAR_CLEARCHOICES: u32 = 34;
pub const VLC_VAR_GETCHOICES: u32 = 36;
pub const VLC_VAR_CHOICESCOUNT: u32 = 38;
pub const VLC_VAR_SETMINMAX: u32 = 39;

#[repr(u32)]
#[non_exhaustive]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum vlc_var_atomic_op {
    VLC_VAR_BOOL_TOGGLE = 0,
    VLC_VAR_INTEGER_ADD = 1,
    VLC_VAR_INTEGER_OR = 2,
    VLC_VAR_INTEGER_NAND = 3,
}

#[repr(C)]
#[derive(Copy, Clone)]
pub union vlc_value_t {
    pub i_int: i64,
    pub b_bool: bool,
    pub f_float: f32,
    pub psz_string: *mut ::std::os::raw::c_char,
    pub p_address: *mut ::std::os::raw::c_void,
    pub coords: vlc_value_t__bindgen_ty_1,
}

#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct vlc_value_t__bindgen_ty_1 {
    pub x: i32,
    pub y: i32,
}

pub type vlc_callback_t = ::std::option::Option<
    unsafe extern "C" fn(
        arg1: *mut vlc_object_t,
        arg2: *const ::std::os::raw::c_char,
        arg3: vlc_value_t,
        arg4: vlc_value_t,
        arg5: *mut ::std::os::raw::c_void,
    ) -> ::std::os::raw::c_int,
>;

pub type vlc_list_callback_t = ::std::option::Option<
    unsafe extern "C" fn(
        arg1: *mut vlc_object_t,
        arg2: *const ::std::os::raw::c_char,
        arg3: ::std::os::raw::c_int,
        arg4: *mut vlc_value_t,
        arg5: *mut ::std::os::raw::c_void,
    ) -> ::std::os::raw::c_int,
>;

extern "C" {
    pub fn var_Create(
        obj: *mut vlc_object_t,
        name: *const ::std::os::raw::c_char,
        type_: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}

extern "C" {
    pub fn var_Destroy(obj: *mut vlc_object_t, name: *const ::std::os::raw::c_char);
}

extern "C" {
    pub fn var_Change(
        obj: *mut vlc_object_t,
        name: *const ::std::os::raw::c_char,
        action: ::std::os::raw::c_int,
        ...
    ) -> ::std::os::raw::c_int;
}

extern "C" {
    pub fn var_Type(
        obj: *mut vlc_object_t,
        name: *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}

extern "C" {
    pub fn var_Set(
        obj: *mut vlc_object_t,
        name: *const ::std::os::raw::c_char,
        val: vlc_value_t,
    ) -> ::std::os::raw::c_int;
}

extern "C" {
    pub fn var_Get(
        obj: *mut vlc_object_t,
        name: *const ::std::os::raw::c_char,
        valp: *mut vlc_value_t,
    ) -> ::std::os::raw::c_int;
}

extern "C" {
    pub fn var_SetChecked(
        arg1: *mut vlc_object_t,
        arg2: *const ::std::os::raw::c_char,
        arg3: ::std::os::raw::c_int,
        arg4: vlc_value_t,
    ) -> ::std::os::raw::c_int;
}

extern "C" {
    pub fn var_GetChecked(
        arg1: *mut vlc_object_t,
        arg2: *const ::std::os::raw::c_char,
        arg3: ::std::os::raw::c_int,
        arg4: *mut vlc_value_t,
    ) -> ::std::os::raw::c_int;
}

extern "C" {
    pub fn var_GetAndSet(
        obj: *mut vlc_object_t,
        name: *const ::std::os::raw::c_char,
        op: ::std::os::raw::c_int,
        value: *mut vlc_value_t,
    ) -> ::std::os::raw::c_int;
}

extern "C" {
    pub fn var_Inherit(
        arg1: *mut vlc_object_t,
        arg2: *const ::std::os::raw::c_char,
        arg3: ::std::os::raw::c_int,
        arg4: *mut vlc_value_t,
    ) -> ::std::os::raw::c_int;
}

extern "C" {
    pub fn var_AddCallback(
        obj: *mut vlc_object_t,
        name: *const ::std::os::raw::c_char,
        callback: vlc_callback_t,
        opaque: *mut ::std::os::raw::c_void,
    );
}

extern "C" {
    pub fn var_DelCallback(
        obj: *mut vlc_object_t,
        name: *const ::std::os::raw::c_char,
        callback: vlc_callback_t,
        opaque: *mut ::std::os::raw::c_void,
    );
}

extern "C" {
    pub fn var_TriggerCallback(obj: *mut vlc_object_t, name: *const ::std::os::raw::c_char);
}

extern "C" {
    pub fn var_AddListCallback(
        arg1: *mut vlc_object_t,
        arg2: *const ::std::os::raw::c_char,
        arg3: vlc_list_callback_t,
        arg4: *mut ::std::os::raw::c_void,
    );
}

extern "C" {
    pub fn var_DelListCallback(
        arg1: *mut vlc_object_t,
        arg2: *const ::std::os::raw::c_char,
        arg3: vlc_list_callback_t,
        arg4: *mut ::std::os::raw::c_void,
    );
}

extern "C" {
    pub fn var_InheritURational(
        obj: *mut vlc_object_t,
        num: *mut ::std::os::raw::c_uint,
        den: *mut ::std::os::raw::c_uint,
        name: *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}

extern "C" {
    pub fn var_LocationParse(
        obj: *mut vlc_object_t,
        mrl: *const ::std::os::raw::c_char,
        prefix: *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}

