/* automatically generated by rust-bindgen 0.66.1 */

#![allow(rustdoc::bare_urls)]
#![allow(rustdoc::broken_intra_doc_links)]
#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]

pub type __time_t = ::std::os::raw::c_long;
pub type __syscall_slong_t = ::std::os::raw::c_long;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct timespec {
    pub tv_sec: __time_t,
    pub tv_nsec: __syscall_slong_t,
}

pub type vlc_tick_t = i64;

extern "C" {
    pub fn vlc_tick_to_str(
        psz_buffer: *mut ::std::os::raw::c_char,
        ticks: vlc_tick_t,
    ) -> *mut ::std::os::raw::c_char;
}

#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct date_t {
    pub date: vlc_tick_t,
    pub i_divider_num: u32,
    pub i_divider_den: u32,
    pub i_remainder: u32,
}

extern "C" {
    pub fn date_Init(date: *mut date_t, num: u32, den: u32);

    pub fn date_Change(date: *mut date_t, num: u32, den: u32);

    pub fn date_Increment(date: *mut date_t, count: u32) -> vlc_tick_t;

    pub fn date_Decrement(date: *mut date_t, count: u32) -> vlc_tick_t;
}

