/* automatically generated by rust-bindgen 0.66.1 */

#![allow(rustdoc::bare_urls)]
#![allow(rustdoc::broken_intra_doc_links)]
#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]

#[repr(u32)]
#[non_exhaustive]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum vlc_player_state {
    VLC_PLAYER_STATE_STOPPED = 0,
    VLC_PLAYER_STATE_STARTED = 1,
    VLC_PLAYER_STATE_PLAYING = 2,
    VLC_PLAYER_STATE_PAUSED = 3,
    VLC_PLAYER_STATE_STOPPING = 4,
}

#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct vlc_player_t {
    _unused: [u8; 0],
}

extern "C" {
    pub fn vlc_player_Lock(arg1: *mut vlc_player_t);

    pub fn vlc_player_Unlock(arg1: *mut vlc_player_t);

    pub fn vlc_player_GetState(player: *mut vlc_player_t) -> vlc_player_state;

    pub fn vlc_player_Pause(player: *mut vlc_player_t);
 
    pub fn vlc_player_Resume(player: *mut vlc_player_t);
}
