/* automatically generated by rust-bindgen 0.66.1 */

#![allow(rustdoc::bare_urls)]
#![allow(rustdoc::broken_intra_doc_links)]
#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]

#[repr(u32)]
#[non_exhaustive]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum vlc_system_dir {
    VLC_PKG_DATA_DIR = 0,
    VLC_PKG_LIB_DIR = 1,
    VLC_PKG_LIBEXEC_DIR = 2,
    VLC_PKG_INCLUDE_DIR_RESERVED = 3,
    VLC_SYSDATA_DIR = 4,
    VLC_LIB_DIR = 5,
    VLC_LIBEXEC_DIR = 6,
    VLC_INCLUDE_DIR_RESERVED = 7,
    VLC_LOCALE_DIR = 8,
}

pub use self::vlc_system_dir as vlc_sysdir_t;
extern "C" {
    pub fn config_GetSysPath(
        dir: vlc_sysdir_t,
        filename: *const ::std::os::raw::c_char,
    ) -> *mut ::std::os::raw::c_char;
}

#[repr(u32)]
#[non_exhaustive]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum vlc_user_dir {
    VLC_HOME_DIR = 0,
    VLC_CONFIG_DIR = 1,
    VLC_USERDATA_DIR = 2,
    VLC_CACHE_DIR = 3,
    VLC_DESKTOP_DIR = 128,
    VLC_DOWNLOAD_DIR = 129,
    VLC_TEMPLATES_DIR = 130,
    VLC_PUBLICSHARE_DIR = 131,
    VLC_DOCUMENTS_DIR = 132,
    VLC_MUSIC_DIR = 133,
    VLC_PICTURES_DIR = 134,
    VLC_VIDEOS_DIR = 135,
    VLC_SNAPSHOTS_DIR = 136,
}

pub use self::vlc_user_dir as vlc_userdir_t;
extern "C" {
    pub fn config_GetUserDir(arg1: vlc_userdir_t) -> *mut ::std::os::raw::c_char;
}
